# Generated by Django 2.0.7 on 2018-08-07 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foodlist', '0002_auto_20180806_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodlist.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Userlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=30)),
                ('list_date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='listdetail',
            name='ldetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodlist.Userlist'),
        ),
    ]
